--- 
# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NovaStark1234/SellStick
build-by-default: true
branches:
- main
projects:
  SellStick:
    path: ""
    icon: "icon.png"
    libs:
    - src: Eric-pm-pl/LibEconomy/LibEconomy
      version: ^1.0.0-alpha
#kkk stupid lint
...
