name: SellStick
main: Nova\SellStick\Main
author: NovaStark1245
api: 5.0.0
version: 2.0.0
depend: BedrockEconomy

permissions:
 sellstick.command.use:
  description: Allow the player use sellstick command
  default: op
